language: java
jdk:
- oraclejdk7
sudo: false
script:
- travis_retry mvn clean install site
- "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && [ ${TRAVIS_BRANCH} = 'master' ] && mvn clean deploy --settings .travis/settings.xml"
notifications:
  slack:
    secure: M0RwmZIRQjLHJgJsVHr2EZUxd+gbGt0T7C3zz8nPeN7+ppap5+bBrE6A3TVzAfR8ZOl6CoxfRi5JnazqzQJmC9/h9kiEPuxBFjB5I2p/AlKRzRrYAOjqHf8JmtCTGzKJTLaDdJzBy5lH2ipys2XO9sPSf6ivfDAG3QzHpUbKCDE=
  email:
  - alexander.willner@tu-berlin.de
  - fiteagle.dev@av.tu-berlin.de
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
env:
  global:
  - secure: OitPkbOYWCDS/g6VSmGIdfq8h24KXErs8wMe/0EsULCrAoteveRqwp1TVRk4NTj9Jqo5kMxowuFqKrRauk9/9lKfCcGJZYV8VZxnUOoIzySBvsAm27QOkl4AVT2PqIhUs1qdPpfIQ5sKJbr7Kmj1xyiI6ltXzbbi8jisEFcblCg=
  - secure: QhyOAAQ0s410bWOIsB1r86yi81szxT4LqDOpiJtUVMcj77YmCSS7JoXIk0xo1aN/IRNRgkkFWXhNnsVTpid1/XK9Sp8FhKi1WU2c1q54ZmKgb+y67x1slm0bOcAzRYUdiMs/InkJcUIm2A/8DVJ1brnlRTzbb/FAzOzg0PYIyHU=
after_success:
- mvn clean test jacoco:report coveralls:report
- curl http://demo.fiteagle.org/trigger.php?c=fiteagle
