language: java
jdk:
- oraclejdk7
script:
- travis_retry mvn clean install site
- "[ ${TRAVIS_PULL_REQUEST} = 'false' ] &amp;&amp; mvn clean deploy--settings .travis/settings.xml"
notifications:
  slack:
    secure: M0RwmZIRQjLHJgJsVHr2EZUxd+gbGt0T7C3zz8nPeN7+ppap5+bBrE6A3TVzAfR8ZOl6CoxfRi5JnazqzQJmC9/h9kiEPuxBFjB5I2p/AlKRzRrYAOjqHf8JmtCTGzKJTLaDdJzBy5lH2ipys2XO9sPSf6ivfDAG3QzHpUbKCDE=
  email:
  - alexander.willner@tu-berlin.de
  - fiteagle.dev@av.tu-berlin.de
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: OitPkbOYWCDS/g6VSmGIdfq8h24KXErs8wMe/0EsULCrAoteveRqwp1TVRk4NTj9Jqo5kMxowuFqKrRauk9/9lKfCcGJZYV8VZxnUOoIzySBvsAm27QOkl4AVT2PqIhUs1qdPpfIQ5sKJbr7Kmj1xyiI6ltXzbbi8jisEFcblCg=
  - secure: QhyOAAQ0s410bWOIsB1r86yi81szxT4LqDOpiJtUVMcj77YmCSS7JoXIk0xo1aN/IRNRgkkFWXhNnsVTpid1/XK9Sp8FhKi1WU2c1q54ZmKgb+y67x1slm0bOcAzRYUdiMs/InkJcUIm2A/8DVJ1brnlRTzbb/FAzOzg0PYIyHU=
after_success:
- mvn clean test jacoco:report coveralls:report
- curl http://trescimo.av.tu-berlin.de/static/trigger.php?c=fiteagle
